# Generated by Django 2.2.5 on 2019-11-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
        ('chats', '0002_chat_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='sticker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='stickers.Sticker'),
        ),
    ]
